### ISSUE TITLE
Crash after running denoiser

### ISSUE THREAD

**Issue by JomW** [ChristopheMoreau/FiNE#5]
Hello Christophe,

I tried to use Intel OID or Nvidia optix for noise reduction, but the program exits when I click the denoise button, do you have any ideas?

Here is the error from the console
`
Warning, Renderman not found (or maybe you have wrong environment variable...
C:/FiNE_v3.33
Traceback (most recent call last):
  File "FINE_v333.py", line 918, in MultiDenoiser
  File "FINE_v333.py", line 1854, in multiDenoiserRun
  File "FINE_v333.py", line 1537, in extractLayerList
ValueError: Invalid format specifier
`

![20240304215519](https://github.com/ChristopheMoreau/FiNE/assets/80466384/307eda0a-50eb-4267-8475-212e875a92c5)

**Comment by ChristopheMoreau** [comment]
Hello, could you try to rename your "file_my file.0001.exr"

For the RenderMan error, FiNE needs RenderMan to be installed on your computer and a "special" exr file coming from your DCC with the denoise option checked (that way the exr has multiple aov's needed to be Denoise with the RenderMan denoiser). If you're using Nvidia nor Intel, you only need normal + albedo like you did.

**Comment by JomW** [comment]
> 您好，您能否尝试重命名您的“file_my file.0001.exr”
> 
> 对于 RenderMan 错误，FiNE 需要在您的计算机上安装 RenderMan，并且需要从您的 DCC 获得一个“特殊”的 exr 文件，并选中 denoise 选项（这样 exr 需要多个 aov 才能使用 RenderMan 降噪器进行降噪）。如果您使用的是 Nvidia 或 Intel，则只需要像以前一样的正常 + 反照率。

Opps, Sorry I didn't realize there was a naming rule. It's working great, thanks for the reply!😀
